name = "QuantikzServer"
uuid = "ecf7fa8d-20db-4f7e-8a17-a8e82751ee81"
authors = ["Stefan Krastanov <stefan@krastanov.org>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
Quantikz = "b0d11df0-eea3-4d79-b4a5-421488cbf74b"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Genie = "5"
HTTP = "1.10.19"
